name: Terraform Destroy

on:
  workflow_call:
    inputs:
      environment:
        description: environment to destroy
        required: true
        type: string
      main-repo:
        description: main repository to be used
        required: true
        type: string
      folder:
        description: folder with the terraform code to be run
        default: "."
        required: false
        type: string

jobs:
  plan:
    name: Plan Destroy on ${{ inputs.environment }} environment
    if: ${{ inputs.environment != 'live' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout Main code
        uses: actions/checkout@v4.2.2
        with:
          path: ${{ inputs.main-repo }}

      - name: Pull the repo changes done on the previous job
        working-directory: ${{ inputs.main-repo }}
        run: git pull

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::148221445737:role/automation/GitHubRole-opsai
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
        run: terraform init

      - name: Terraform select workspace
        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          echo "TF_WORKSPACE=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Terraform Plan Destroy
        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
        run: terraform plan -destroy

  approval:
    name: Manual Approval
    needs: [plan]
    if: ${{ inputs.environment != 'live' }}
    runs-on: ubuntu-latest
    environment:
      name: destroy-approval

    steps:
      - name: Waiting for approval
        run: echo "Approved. Continuing to destroy."

  destroy:
    name: Destroy resources on ${{ inputs.environment }} environment
    needs: [approval]
    if: ${{ inputs.environment != 'live' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Main code
        uses: actions/checkout@v4.2.2
        with:
          path: ${{ inputs.main-repo }}

      - name: Pull the repo changes done on the previous job
        working-directory: ${{ inputs.main-repo }}
        run: git pull

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          role-to-assume: arn:aws:iam::148221445737:role/automation/GitHubRole-opsai
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.7.0"

      - name: Terraform Init
        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
        run: terraform init

      - name: Terraform select workspace
        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
        run: |
          terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}
          echo "TF_WORKSPACE=${{ inputs.environment }}" >> $GITHUB_ENV

      - name: Terraform Destroy
        working-directory: ${{ inputs.main-repo }}/${{ inputs.folder }}
        run: terraform destroy --auto-approve
